services:
  web:
    build: ./RavenAPI/.
    ports:
      - '8080:80'
    tags:
      - RavenAPI:dev

  db:
    build:
      context: ./DbPsql/.
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    tags:
      - RavenAPI:DbPsql
