services:
  web:
    build: ./RavenAPI/.
    ports:
      - '8080:80'

  db:
    build:
      context: ./DbPsql/.
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
