version: '0.1'

services:
  db:
    build:
      context: ./DbPsql/.
    container_name: raven
    restart: always
    secrets: 
      - my_secrets
    environment:
<<<<<<< HEAD
      - POSTGRES_USER='{/run/secrets/my_secrets/POSTGRES_USER}'
      - POSTGRES_PASSWORD='{/run/secrets/my_secrets/POSTGRES_PASSWORD}'
=======
      POSTGRES_USER: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
>>>>>>> 2b35a3a8f6bc8c7b04441c10972ed6b139faea1c
    ports:
      - 5432:5432

  api:
    build:
      context: .
    container_name: api
    environment:
      ASPNETCORE_Environment: Development
    ports:
      - 8080:80
    depends_on:
      - db

secrets:
<<<<<<< HEAD
  my_secrets:
    file: 'C:\Users\TBeck\AppData\Roaming\Microsoft\UserSecrets\39aa9da3-7917-4658-8bea-83da217705d1\secrets.json'
=======
  POSTGRES_PASSWORD:
    file: C:\Users\TBeck\AppData\Roaming\Microsoft\UserSecrets\39aa9da3-7917-4658-8bea-83da217705d1\secrets.json
  POSTGRES_USER:
    file: C:\Users\TBeck\AppData\Roaming\Microsoft\UserSecrets\39aa9da3-7917-4658-8bea-83da217705d1\secrets.json
>>>>>>> 2b35a3a8f6bc8c7b04441c10972ed6b139faea1c
