services:
  web:
    build: ./RavenAPI/.
    ports:
      - '8080:80'

  db:
    image: postgres
    build:
      context: ./DbPsql/.
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
