services:
  web:

    build: .
    ports:
      - '8080:80'

  db:
    build:
      context: ./DbPsql/.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
