version: '0.1'

services:
  db:
    build:
      context: ./DbPsql/.
    container_name: raven
    restart: always
    secrets: 
      - my_secrets
    environment:
      POSTGRES_USER: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
    ports:
      - 5432:5432

  api:
    build:
      context: .
    container_name: api
    environment:
      ASPNETCORE_Environment: Development
    ports:
      - 8080:80
    depends_on:
      - db
secrets:
  my_secrets:
    file: 'C:\Users\TBeck\AppData\Roaming\Microsoft\UserSecrets\39aa9da3-7917-4658-8bea-83da217705d1\secrets.json'