services:
  db:
    build:
      context: ./DbPsql/.
    container_name: raven
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  api:
    build:
      context: .
    container_name: api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ASPNETCORE_Environment: Development
    secrets:
      - my_secrets.json
    ports:
      - 8080:80
    depends_on:
      - db
secrets:
  my_secrets.json:
    file: C:\Users\TBeck\AppData\Roaming\Microsoft\UserSecrets\39aa9da3-7917-4658-8bea-83da217705d1\secrets.json
