name: Docker Image CI

on:
  push:
  
    branches: ['master', 'test']
  pull_request:
    branches: ['master', 'test']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        working-directory: ./DbPsql
        run: docker build . --file Dockerfile --tag ravendb:$(date +%s)
