name: Docker Image RavenAPI

on:
  push:

    branches: ['master', 'test']
  pull_request:
    branches: ['master', 'test']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        working-directory: ./RavenAPI
        run: docker build . --file Dockerfile --tag ravenapi:$(date +%s)
